version: "3.8"

services:
  auth:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HEALTH_ENABLED: true
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: 
      - start-dev 
      - --import-realm
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 10s
      timeout: 5s
      retries: 5
  tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      auth:
        condition: service_healthy
    env_file: test.env
networks:
  amakids_network:
