version: "3.8"

services:
  auth:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8180"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: 
      - start-dev 
      - --http-port=8180
      - --import-realm
  tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - auth
    env_file: test.env
networks:
  amakids_network: